### ISSUE TITLE
Frame rates is much lower  than the paper said with davis346，Only 30Hz！

### ISSUE THREAD

**Issue by xji-apex** [vbrebion/rt_of_low_high_res_event_cameras#2]
Hello !!! Thank you for your open source !!! It's an amazing job!

But when I test on my devices， the frame rate is only 30Hz. 
My operating devices are davis346， NVIDIA GeForce GTX 1050, and Core™ i5-7300HQ CPU @ 2.50GHz × 4 .

It may be caused by different equipment.
But It is much lower than 250 Hz as the paper said.
So I want to know the possible reasons for the lower frame rate.

Thanks a ton!

**Comment by xji-apex** [comment]
![sendpix0](https://user-images.githubusercontent.com/71243343/153376913-a323bbb2-8d00-43fa-a33d-f545eec5342d.jpg)

**Comment by vbrebion** [comment]
Hi,

Thank you very much for your interest in our code and your comments!

Regarding your issue, it is indeed quite strange.
In order to pinpoint more easily the origin of the issue, do you use one of the launchfiles given in the repo (for instance, the `davis346_replay.launch` one, since you mention you use a davis346 camera), or have you created a customized one?

In the second case, could you share it so that I may have a look at it and try to track the issue?

Best,
Vincent

**Comment by xji-apex** [comment]
Yeah, I created a customized launch file（davis346_live.launch）to run in real-time.
The davis346_live.launch is as followed：

<launch>
  
  <node name="davis_ros_driver" pkg="davis_ros_driver" type="davis_ros_driver" output="screen"/>

  
  <node name="edges" pkg="rt_of_low_high_res_event_cameras" type="edges_node_live" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="topic" type="string" value="/dvs/events"/>
    <param name="accumulation_window" type="int" value="25"/>
    <param name="height" type="int" value="260"/>
    <param name="width" type="int" value="346"/>
    <param name="queues_size" type="int" value="1"/>
    
  </node>

  
  <node name="denoising_filling" pkg="rt_of_low_high_res_event_cameras" type="denoising_filling_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="denoising_min_neighbours" type="int" value="1"/>
    <param name="filling_min_neighbours" type="int" value="4"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  
  <node name="distance_surface" pkg="rt_of_low_high_res_event_cameras" type="distance_surface_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="distance_surface_formulation" type="string" value="exponential"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  
  <node name="optical_flow" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="pyramidal_flow_levels" type="int" value="3"/>
    <param name="max_flow" type="double" value="15.0"/>
    <rosparam param="gammas">[50.0, 250.0, 500.0]</rosparam>
    <rosparam param="smooth_iterations">[50, 25, 5]</rosparam>
    <param name="queues_size" type="int" value="1"/>
  </node>

  
  <node name="optical_flow_viz" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_viz_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="visualization_method" type="string" value="colors"/>
    <param name="clip_flow" type="double" value="-1"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  
  <node name="image_view" pkg="rqt_image_view" type="rqt_image_view" args="/rt_of_low_high_res_event_cameras/optical_flow_viz"/>

</launch>

BTW, I run the provided davis346_replay.launch file. The frame rate could reach 40Hz. It's different, but also lower than expected!

Thank you for your kind of attention and Looking forward to your reply ! ! !

**Comment by xji-apex** [comment]
Yeah, I created a customized launch file（davis346_live.launch）to run in real-time.
The davis346_live.launch is as followed：

```
<launch>
  <!-- Davis driver -->
  <node name="davis_ros_driver" pkg="davis_ros_driver" type="davis_ros_driver" output="screen"/>

  <!-- Edges node -->
  <node name="edges" pkg="rt_of_low_high_res_event_cameras" type="edges_node_live" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="topic" type="string" value="/dvs/events"/>
    <param name="accumulation_window" type="int" value="25"/>
    <param name="height" type="int" value="260"/>
    <param name="width" type="int" value="346"/>
    <param name="queues_size" type="int" value="1"/>
    <!--<param name="calibration_file" type="str" value="..."/>-->
  </node>

  <!-- Denoising & filling node -->
  <node name="denoising_filling" pkg="rt_of_low_high_res_event_cameras" type="denoising_filling_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="denoising_min_neighbours" type="int" value="1"/>
    <param name="filling_min_neighbours" type="int" value="4"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Distance surface node -->
  <node name="distance_surface" pkg="rt_of_low_high_res_event_cameras" type="distance_surface_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="distance_surface_formulation" type="string" value="exponential"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Optical flow node -->
  <node name="optical_flow" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="pyramidal_flow_levels" type="int" value="3"/>
    <param name="max_flow" type="double" value="15.0"/>
    <rosparam param="gammas">[50.0, 250.0, 500.0]</rosparam>
    <rosparam param="smooth_iterations">[50, 25, 5]</rosparam>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Optical flow visualization node -->
  <node name="optical_flow_viz" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_viz_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="visualization_method" type="string" value="colors"/>
    <param name="clip_flow" type="double" value="-1"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Display -->
  <node name="image_view" pkg="rqt_image_view" type="rqt_image_view" args="/rt_of_low_high_res_event_cameras/optical_flow_viz"/>

</launch>
```



BTW, I run the provided davis346_replay.launch file. The frame rate could reach 40Hz. It's different, but also lower than expected!

Thank you for your kind of attention and Looking forward to your reply ! ! !

**Comment by vbrebion** [comment]
Thank you very much for the details!

Regarding the `davis346_replay.launch` file, first, it is normal to have a 40Hz output with its default configuration, as the edges node is set to accumulate events over a time period of 25ms (line 6 of the file):

```xml
<param name="accumulation_window" type="int" value="25"/>
```

If you want to reach a 250Hz output, you can lower this setting to an accumulation window of 4ms:

```xml
<param name="accumulation_window" type="int" value="4"/>
```

These are the results I obtained on my computer by setting this value (close to the theoretical limit of 250Hz, you might have slightly different results based on your setup):
![davis346_4ms](https://user-images.githubusercontent.com/61004974/153564000-fbc70fbe-04c1-48c4-8585-9960f6ae471f.png)

For the live version, however, it seems that the output rate is constrained by two elements:

1. the accumulation window for the edge images, set to 25ms;
2. the output rate of the camera.

Solving issue (1) is easy, as you only have to replace this value in your `davis346_live.launch` file (line 8) as described above.

For issue (2), however, you need to dynamically reconfigure your camera after launching it, to increase its output rate.\
To do so, once you have executed the `roslaunch rt_of_low_high_res_event_cameras davis346_live.launch` command, simply execute the `rosrun rqt_reconfigure rqt_reconfigure` command in a second terminal. You should obtain a window similar to the following one:
![rqt_reconfigure](https://user-images.githubusercontent.com/61004974/153565733-36c75136-8d92-40c6-b001-de749483f3b0.png)

You then only need to modify the first parameter (`streaming_rate`) to a higher value (or 0 to remove any limit), to allow the camera to send more packets of events per second.

By doing both steps on my computer and by using a live DAVIS240C camera, I obtained the following results:
![image](https://user-images.githubusercontent.com/61004974/153566307-752032cf-be75-496f-a514-aa32aa952541.png)

As you can see, I am still quite far from a 250Hz output, but I think that it comes from the DAVIS240C camera, which may not be able to send events at a 250Hz rate. As a results, most of the edge images produced are empty, and therefore get discarded rather than being sent. I am curious to see if the DAVIS346 camera has a similar behavior, or if it can handle higher rates.

In any case, do not hesitate to update me once you have tried this solution on your side, and ask questions if you have any remaining issue!

Best,
Vincent

**Comment by vbrebion** [comment]
Something I also forgot to mention, and that might interest you, is that the "replay" code is configured to mimic the output rate of what the "live" code would produce (i.e., if an accumulation window of 25ms is asked, then the code will output edge images every 25ms, even if it took it much less time to extract the events and create the images).

You can circumvent this behavior by commenting out the following line in the `edges_node_replay.cpp` file (line 110):

```cpp
this_thread::sleep_for(chrono::milliseconds(accumulation_window) - elapsed_time);
```

After commenting out this line on my computer, these are the results I was able to obtain:
![image](https://user-images.githubusercontent.com/61004974/153570679-95a9c64c-cf0f-425d-88a1-3ecaef1241bf.png)

As you can see, I was able to obtain an output rate for the edge images alone greater than 4400Hz.\
The main issue is that not constraining the output rate of the nodes leads to the CPU and GPU being used to their maximum. In the capture above for instance, the distance surface node takes too much resources on the GPU, limiting the performances of the optical flow node, limiting it to a 183Hz output.

**Comment by xji-apex** [comment]
Thanks very much!!!
The behavior of davis346 is similar to yours.  But Its rate is lower than davis240. I guess it's because of the higher resolution and the limitations of my computer?
According to your methods， The davis346's performance on my computer is as followed:
(1)For davis346_reply.launch, Set the value of accumulation_window to 4.
![sendpix4](https://user-images.githubusercontent.com/71243343/153698943-1795499b-adca-45f5-ab0f-aeee07aa024b.jpg)

(2)For davis346_live.launch, It's mainly limited by the camera's output rate.(output rate:0)
![sendpix2](https://user-images.githubusercontent.com/71243343/153698837-908fd618-a481-4f40-82a1-89ff8eb60b2b.jpg)

At last, Thank you so much for your sharing work and effective reply！
Good luck, I'll follow！

**Comment by vbrebion** [comment]
Perfect!

As you said, I also believe that the higher resolution and your computer specifications might not allow you to reach the theoretical limit of 250Hz.\
However, as you might have observed, going to this limit might not be the best choice, as accumulating events over 4ms at such a low resolution produces quite unstable results. I would advise to stick to slightly lower rates (e.g., 40Hz as default), which should give better optical flow outputs.

Once again, if you have any other question or problem, do not hesitate to open another issue, I would be happy to help you.
And thanks again for the kind words!
